name: GitHub-Profile-3D-Contrib

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, closed, reopened, synchronize]
    branches:
      - '*'  # This triggers on any branch for pull requests
  issues:
    types: [opened, closed]
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GraphKey }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
